namespace:
  name: prod

service:
  port: 80
  type: ClusterIP

image:
  repository: nginx
  tag: 1.17.0
  pullPolicy: IfNotPresent

replicaCount: 2

resources:
  requests:
    cpu: 30m
    memory: 128Mi
  limits:
    cpu: 60m
    memory: 256Mi

configmap:
  data: 'version: 1.17.0'
