namespace:
  name: sandbox

service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: dunkbing/techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

containerPort: 3111

livenessProbe:
  path: /healthz

readinessProbe::
  path: /healthz
